window.GOLDHAVEN_ABI = {
  erc20: [
    'function decimals() view returns (uint8)',
    'function balanceOf(address) view returns (uint256)',
    'function allowance(address owner,address spender) view returns (uint256)',
    'function approve(address spender,uint256 amount) returns (bool)',
    'function totalSupply() view returns (uint256)'
  ],
  hook: [
    'function K_SUPPLY() view returns (uint256)',
    'function S() view returns (uint256)',
    'function arenaVaultEth() view returns (uint256)',
    'function ethCum() view returns (uint256)',
    'function curveReserveEth() view returns (uint256)',
    'function marginalPrice() view returns (uint256)',
    'function totalMintedFair() view returns (uint256)',
    'function depositArenaFee() payable',
    'function arenaController() view returns (address)',
    'function NFT_THRESHOLD_USD_WAD() view returns (uint256)',
    'function MAX_BUY_WEI() view returns (uint256)',
    'function COOLDOWN_BLOCKS() view returns (uint256)',
    'function ENTROPY_BLOCKS() view returns (uint256)',
    'function GENESIS_BLOCK() view returns (uint256)',
    'function lastBuyBlock(address account) view returns (uint256)'
  ],
  nft: [
    'function nextTokenId() view returns (uint256)',
    'function ownerOf(uint256 tokenId) view returns (address)',
    'function approve(address to,uint256 tokenId)',
    'function getApproved(uint256 tokenId) view returns (address)',
    'function isApprovedForAll(address owner,address operator) view returns (bool)',
    'function setApprovalForAll(address operator,bool approved)',
    'function transferFrom(address from,address to,uint256 tokenId)',
    'function safeTransferFrom(address from,address to,uint256 tokenId)',
    'function burn(uint256 tokenId)',
    'function cardOf(uint256 tokenId) view returns (tuple(uint256 tokenId,uint256 stakeId,uint64 stakeTime,uint32 buyUsd,uint32 vaultAvgUsd,uint16 attack,uint16 defense,uint16 speed,uint16 hp,uint8 classId,uint8 element,uint8 beast,uint8 attrSkill,uint8 starterSkill,uint8 beastSkill,uint8 finisherSkill,uint8 fate))',
    'function imageURI(uint256 tokenId) view returns (string)',
    'function tokenURI(uint256 tokenId) view returns (string)',
    'function comboImageURI(uint8 classId,uint8 beast) view returns (string)'
  ],
  vault: [
    'error BadFee()',
    'error NotStakeOwner()',
    'error AlreadyStaked()',
    'error NotStaked()',
    'error ArenaFull()',
    'error ArenaLocked()',
    'error ZeroAmount()',
    'error TransferFailed()',
    'error HookNotSet()',
    'error ArenaInProgress()',
    'error InvalidNftTransfer()',
    'function NFT_STAKE_FEE() view returns (uint256)',
    'function VALIDATOR_THRESHOLD_USD_WAD() view returns (uint256)',
    'function totalTokenStaked() view returns (uint256)',
    'function tokenStakeOf(address user) view returns (uint256)',
    'function stakeIdOfToken(uint256 tokenId) view returns (uint256)',
    'function nftStakes(uint256 stakeId) view returns (address owner,uint256 tokenId,uint64 stakedAt,bool active)',
    'function stakeOwnerOfToken(uint256 tokenId) view returns (address)',
    'function lockedInActiveArena(uint256 tokenId) view returns (bool)',
    'function arenaOfToken(uint256 tokenId) view returns (address)',
    'function arenaFinishedAtOfToken(uint256 tokenId) view returns (uint256)',
    'function isArenaParticipant(uint256 tokenId) view returns (bool)',
    'function getArenaParticipants() view returns (uint256[])',
    'function isValidator(address user) view returns (bool)',
    'function averageLockUsdWad24h() view returns (uint256)',
    'function averageTokenAmount24h() view returns (uint256)',
    'function userAverageTokenAmount24h(address user) view returns (uint256)',
    'function nextDividendEpochId() view returns (uint256)',
    'function pendingUndistributedDividends() view returns (uint256)',
    'function dividendEpochs(uint256 epochId) view returns (uint64 start,uint64 end,uint256 amount,uint256 totalTokenSeconds,uint256 claimed)',
    'function dividendClaimed(uint256 epochId,address user) view returns (bool)',
    'function previewDividend(uint256 epochId,address user) view returns (uint256 amount,uint256 userTokenSeconds)',
    'function isArenaLockWindow() view returns (bool)',
    'function isNftActionLocked() view returns (bool)',
    'function stakeToken(uint256 amount)',
    'function unstakeToken(uint256 amount)',
    'function claimDividend(uint256 epochId) returns (uint256 amount)',
    'function claimDividends(uint256[] epochIds) returns (uint256 total)',
    'function stakeNftForArena(uint256 tokenId) payable returns (uint256 stakeId)',
    'function unstakeNftFromArena(uint256 stakeId)'
  ],
  arenaFactory: [
    'function arenaOfDay(uint256 dayId) view returns (address)',
    'function arenaOfId(uint256 arenaId) view returns (address)',
    'function arenaCount() view returns (uint256)',
    'function activeArena() view returns (address)',
    'function latestArena() view returns (address)',
    'function latestFinishedArena() view returns (address)',
    'function dailyLimitEnabled() view returns (bool)',
    'function testMode() view returns (bool)',
    'function setTestMode(bool enabled)',
    'function setDailyLimitEnabled(bool enabled)',
    'function isOpenWindow() view returns (bool)',
    'function syncArenaStatus()',
    'function openDailyArena() returns (address arena)',
    'function openDailyArena(uint256[] participantTokenIds) returns (address arena)',
    'function openArena() returns (address arena)'
  ],
  arena: [
    'function dayId() view returns (uint256)',
    'function currentRoundNumber() view returns (uint8)',
    'function nextMatchIndex() view returns (uint256)',
    'function currentRoundMatchCount() view returns (uint256)',
    'function currentRoundVerifiedMatches() view returns (uint256)',
    'function currentRoundRemaining() view returns (uint256)',
    'function currentRoundProgress() view returns (uint256 verified,uint256 total)',
    'function currentRound(uint256 index) view returns (uint256)',
    'function nextRound(uint256 index) view returns (uint256)',
    'function getCurrentRound() view returns (uint256[])',
    'function getNextRound() view returns (uint256[])',
    'function matchTokens(uint256 matchIndex) view returns (uint256 tokenA,uint256 tokenB,bool verified,uint256 winner)',
      'function matchCount(uint8 round) view returns (uint256)',
      'function getMatch(uint8 round,uint256 matchIndex) view returns (uint8 round_,uint256 matchIndex_,uint256 tokenA,uint256 tokenB,uint256 winner,uint256 loser,bool verified,address validator)',
      'function entrantCount() view returns (uint256)',
      'function entrantAt(uint256 index) view returns (uint256 tokenId,address owner)',
      'function finalRoundNumber() view returns (uint8)',
      'function top32Count() view returns (uint256)',
      'function top32At(uint256 index) view returns (uint256 rank,uint256 tokenId,address owner)',
    'function matchVerified(uint8 round,uint256 matchIndex) view returns (bool)',
    'function matchWinner(uint8 round,uint256 matchIndex) view returns (uint256)',
    'function matchLoser(uint8 round,uint256 matchIndex) view returns (uint256)',
    'function finished() view returns (bool)',
    'function championTokenId() view returns (uint256)',
    'function totalVerifications() view returns (uint256)',
    'function validatorVerifications(address validator) view returns (uint256)',
    'function pendingRewards(address) view returns (uint256)',
    'function pendingBattleRewards(address) view returns (uint256)',
    'function pendingValidatorRewards(address) view returns (uint256)',
    'function totalPendingRewards() view returns (uint256)',
    'function totalPendingBattleRewards() view returns (uint256)',
    'function totalPendingValidatorRewards() view returns (uint256)',
    'function claimReward() returns (uint256 battleAmount,uint256 validatorAmount)',
    'function claimBattleReward() returns (uint256 amount)',
    'function claimValidatorReward() returns (uint256 amount)',
    'function verifyNextMatch()',
    'function verifyMatch(uint256 matchIndex)',
    'function finishSingleEntrant()',
    'function advanceRound()'
  ],
  marketplace: [
    'function listings(uint256 tokenId) view returns (address seller,uint256 price)',
    'function list(uint256 tokenId,uint256 price)',
    'function cancel(uint256 tokenId)',
    'function buy(uint256 tokenId)'
  ],
  priceOracle: [
    'function ethToUsdWad(uint256 ethWei) view returns (uint256 usdWad)',
    'function ghvToUsdWad(uint256 ghvAmount) view returns (uint256 usdWad)',
    'function ethUsdWad() view returns (uint256)',
    'function ghvUsdWad() view returns (uint256)',
    'function ghvHook() view returns (address)'
  ],
  v4SwapRouter: [
    'function buy(tuple(address currency0,address currency1,uint24 fee,int24 tickSpacing,address hooks) key,uint256 minGhvOut) payable returns (int256 delta)',
    'function sell(tuple(address currency0,address currency1,uint24 fee,int24 tickSpacing,address hooks) key,uint256 ghvIn,uint256 minEthOut) returns (int256 delta)',
    'function swap(tuple(address currency0,address currency1,uint24 fee,int24 tickSpacing,address hooks) key,tuple(bool zeroForOne,int256 amountSpecified,uint160 sqrtPriceLimitX96) params,address recipient) payable returns (int256 delta)',
    'function POOL_MANAGER() view returns (address)'
  ],
  poolManager: [
    'function initialize(tuple(address currency0,address currency1,uint24 fee,int24 tickSpacing,address hooks) key,uint160 sqrtPriceX96) returns (int24 tick)'
  ]
};
